dovecot_config_version = 2.4.3
dovecot_storage_version = 2.4.3
protocols = imap
listen = *
log_path = /var/log/mailcot.log

mail_home = /var/mail%{user | domain}/%{user | username}
mail_uid = 5000
mail_gid = 5000
mail_driver = maildir
mail_path = ~/Maildir

auth_allow_cleartext = yes
auth_mechanisms = plain login

ssl = no

passdb static {
    password = secure_password
    fields {
        proxy = yes
        host = 127.0.0.1
    }
}

service doveadm {
    unix_listener doveadm {
        mode = 0600
        user = root
    }
}