dovecot_config_version = 2.4.3
dovecot_storage_version = 2.4.3
protocols = imap
listen = *

service doveadm {
    unix_listener doveadm {
        mode = 0600
        user = root
    }
}

!include conf.d/*.conf